// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestCert.API.Data;

#nullable disable

namespace TestCert.API.data.Migrations
{
    [DbContext(typeof(TestCertContext))]
    [Migration("20260420001125_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestCert.API.Models.Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentId"));

                    b.Property<bool>("EquipActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EquipDateCreate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EquipDescription")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EquipKtId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateOnly>("EquipLastTest")
                        .HasColumnType("date");

                    b.Property<string>("EquipPlasticTagId")
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.HasKey("EquipmentId");

                    b.HasIndex("TestId");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("TestCert.API.Models.Test", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KtReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TestId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("TestCert.API.Models.Equipment", b =>
                {
                    b.HasOne("TestCert.API.Models.Test", "Test")
                        .WithMany("TestEquipments")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("TestCert.API.Models.Test", b =>
                {
                    b.Navigation("TestEquipments");
                });
#pragma warning restore 612, 618
        }
    }
}
